// This file was auto-generated by ML.NET Model Builder.

using Core.Entities;
using Microsoft.ML;
using Microsoft.ML.Data;
namespace Analysis
{
    public partial class AnalysisModel
    {
        private static string MLNetModelPath = new FileInfo("AnalysisModel.mlnet").FullName;

        public static readonly Lazy<PredictionEngine<FeedbackInput, FeedbackOutput>> PredictEngine = new Lazy<PredictionEngine<FeedbackInput, FeedbackOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<FeedbackInput, FeedbackOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<FeedbackInput, FeedbackOutput>(mlModel);
        }

        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(FeedbackInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(FeedbackOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        private static IEnumerable<string> GetLabels(FeedbackOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("Sentiment");
            if (labelColumn == null)
            {
                throw new Exception("Sentiment column not found. Make sure the name searched for matches the name in the schema.");
            }

            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        public static FeedbackOutput Predict(FeedbackInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
